name:
  First Cron Job
on:
  schedule:
    - cron: "53 12 * * *"
  workflow_dispatch:
  
jobs:
  cron:
    runs-on: windows-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
